In [1]:
import keras
import pandas as pd
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
import matplotlib.pyplot as plt

Using TensorFlow backend.


In [2]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0   540.0                 0.0      0.0  162.0               2.5   
1   540.0                 0.0      0.0  162.0               2.5   
2   332.5               142.5      0.0  228.0               0.0   
3   332.5               142.5      0.0  228.0               0.0   
4   198.6               132.4      0.0  192.0               0.0   

   Coarse Aggregate  Fine Aggregate  Age  Strength  
0            1040.0           676.0   28     79.99  
1            1055.0           676.0   28     61.89  
2             932.0           594.0  270     40.27  
3             932.0           594.0  365     41.05  
4             978.4           825.5  360     44.30

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

Cement  Blast Furnace Slag      Fly Ash        Water  \
count  1030.000000         1030.000000  1030.000000  1030.000000   
mean    281.167864           73.895825    54.188350   181.567282   
std     104.506364           86.279342    63.997004    21.354219   
min     102.000000            0.000000     0.000000   121.800000   
25%     192.375000            0.000000     0.000000   164.900000   
50%     272.900000           22.000000     0.000000   185.000000   
75%     350.000000          142.950000   118.300000   192.000000   
max     540.000000          359.400000   200.100000   247.000000   

       Superplasticizer  Coarse Aggregate  Fine Aggregate          Age  \
count       1030.000000       1030.000000     1030.000000  1030.000000   
mean           6.204660        972.918932      773.580485    45.662136   
std            5.973841         77.753954       80.175980    63.169912   
min            0.000000        801.000000      594.000000     1.000000   
25%            0.000000        932.000000      730.950000     7.000000   
50%            6.400000        968.000000      779.500000    28.000000   
75%           10.200000       1029.400000      824.000000    56.000000   
max           32.200000       1145.000000      992.600000   365.000000   

          Strength  
count  1030.000000  
mean     35.817961  
std      16.705742  
min       2.330000  
25%      23.710000  
50%      34.445000  
75%      46.135000  
max      82.600000

In [5]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [6]:
predictors.head()

Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0   540.0                 0.0      0.0  162.0               2.5   
1   540.0                 0.0      0.0  162.0               2.5   
2   332.5               142.5      0.0  228.0               0.0   
3   332.5               142.5      0.0  228.0               0.0   
4   198.6               132.4      0.0  192.0               0.0   

   Coarse Aggregate  Fine Aggregate  Age  
0            1040.0           676.0   28  
1            1055.0           676.0   28  
2             932.0           594.0  270  
3             932.0           594.0  365  
4             978.4           825.5  360

In [7]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [8]:
n_cols = predictors.shape[1] # number of predictors

# Part A

In [9]:
# define regression model
def regression_model_A():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [10]:
from sklearn.model_selection import train_test_split

MSE_list=[]

i = 0
while i < 50:
    print("This is No.", i, "Network trained")
    model = regression_model_A()
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=0)
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, verbose=2)
    scores = model.evaluate(X_test, y_test, verbose=0)
    MSE_list.append(scores)  
    i = i+1
    
print("Mean Squared Error list:") 
MSE_list

This is No. 0 Network trained
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 1s - loss: 32282.3910 - val_loss: 22733.2213
Epoch 2/50
 - 1s - loss: 15717.7337 - val_loss: 9389.0246
Epoch 3/50
 - 0s - loss: 5539.4427 - val_loss: 2700.1552
Epoch 4/50
 - 0s - loss: 1839.2544 - val_loss: 1511.6695
Epoch 5/50
 - 0s - loss: 1456.8275 - val_loss: 1415.1001
Epoch 6/50
 - 0s - loss: 1364.4817 - val_loss: 1331.6930
Epoch 7/50
 - 0s - loss: 1282.0963 - val_loss: 1256.3609
Epoch 8/50
 - 0s - loss: 1207.6939 - val_loss: 1188.9749
Epoch 9/50
 - 0s - loss: 1141.9716 - val_loss: 1125.4462
Epoch 10/50
 - 0s - loss: 1084.7766 - val_loss: 1073.5979
Epoch 11/50
 - 1s - loss: 1030.6943 - val_loss: 1021.3249
Epoch 12/50
 - 0s - loss: 980.2932 - val_loss: 978.5996
Epoch 13/50
 - 1s - loss: 937.9045 - val_loss: 935.4887
Epoch 14/50
 - 0s - loss: 898.7044 - val_loss: 895.7702
Epoc

[289.39066159146506,
 185.4536693782868,
 92.48111889045987,
 231.70860996678422,
 453.6433151887073,
 144.1926744331434,
 85.27047854179703,
 182.35996584599073,
 121.51621587068132,
 86.35920247445215,
 93.63666489980753,
 149.7030757669492,
 1737.923648772502,
 163.66982871737682,
 130.58867810690674,
 116.4738374481695,
 120.80115069540574,
 242.46068837187437,
 97.79150260999364,
 397.8804890160422,
 310.28663195761277,
 79.7862619443233,
 95.93129804296402,
 166.55918094178233,
 98.81559754652498,
 1342.0969384449586,
 90.83719746117453,
 227.29751621480898,
 331.1932589336506,
 105.80898739219097,
 192.93386821067836,
 184.74465102902508,
 185.33518088133977,
 142.74297592014943,
 143.19880535533127,
 1980.7095315186336,
 151.9309967189159,
 107.53338697118667,
 153.79613368951001,
 1964.7829937487359,
 114.89042098159543,
 136.63846674551857,
 931.0498892281048,
 131.99038859247003,
 228.741161655068,
 108.11041607903046,
 68.08781702232979,
 78.96764745372785,
 101.27371928144

In [11]:
MSE_array = np.array(MSE_list)
MSE_array

array([ 289.39066159,  185.45366938,   92.48111889,  231.70860997,
        453.64331519,  144.19267443,   85.27047854,  182.35996585,
        121.51621587,   86.35920247,   93.6366649 ,  149.70307577,
       1737.92364877,  163.66982872,  130.58867811,  116.47383745,
        120.8011507 ,  242.46068837,   97.79150261,  397.88048902,
        310.28663196,   79.78626194,   95.93129804,  166.55918094,
         98.81559755, 1342.09693844,   90.83719746,  227.29751621,
        331.19325893,  105.80898739,  192.93386821,  184.74465103,
        185.33518088,  142.74297592,  143.19880536, 1980.70953152,
        151.93099672,  107.53338697,  153.79613369, 1964.78299375,
        114.89042098,  136.63846675,  931.04988923,  131.99038859,
        228.74116166,  108.11041608,   68.08781702,   78.96764745,
        101.27371928,  127.49882332])

In [12]:
print("The mean of the Mean Squared Error list: %.2f" % MSE_array.mean())
print("The standard deviation of the Mean Squared Error list: %.2f" % MSE_array.std())

The mean of the Mean Squared Error list: 304.14
The standard deviation of the Mean Squared Error list: 454.58


# Part B

In [13]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()
n_cols = predictors_norm.shape[1] # number of predictors

In [14]:
from sklearn.model_selection import train_test_split

MSE_list=[]

i = 0
while i < 50:
    model = regression_model_A()
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=0)
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, verbose=2)
    scores = model.evaluate(X_test, y_test, verbose=0)
    MSE_list.append(scores)  
    i = i+1

print("Mean Squared Error list:") 
MSE_list

Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 3s - loss: 49518.6373 - val_loss: 18355.2365
Epoch 2/50
 - 0s - loss: 9021.6133 - val_loss: 5171.5757
Epoch 3/50
 - 0s - loss: 5494.8673 - val_loss: 4762.5372
Epoch 4/50
 - 1s - loss: 4800.3834 - val_loss: 4241.2231
Epoch 5/50
 - 0s - loss: 4337.4646 - val_loss: 3872.3745
Epoch 6/50
 - 1s - loss: 3946.0661 - val_loss: 3598.4254
Epoch 7/50
 - 0s - loss: 3646.3869 - val_loss: 3364.2750
Epoch 8/50
 - 0s - loss: 3377.8826 - val_loss: 3155.7945
Epoch 9/50
 - 0s - loss: 3137.1693 - val_loss: 2965.5081
Epoch 10/50
 - 0s - loss: 2928.0752 - val_loss: 2796.7893
Epoch 11/50
 - 0s - loss: 2753.6146 - val_loss: 2632.9916
Epoch 12/50
 - 0s - loss: 2587.0507 - val_loss: 2489.3274
Epoch 13/50
 - 0s - loss: 2460.0012 - val_loss: 2354.6029
Epoch 14/50
 - 0s - loss: 2321.8200 - val_loss: 2227.9796
Epoch 15/50
 - 0s - loss: 2192.5647 - val_loss: 2118.0199
Epoch 16/50
 - 0s - loss: 2082.0621 - val_loss: 2006.9513
Epoch 17/50
 - 0s - loss: 1971.79

[370.82769706256954,
 233.00636968026268,
 510.64090884310525,
 118.4243472201153,
 250.89545369071095,
 123.2001602024708,
 289.7779230901724,
 611.1452700914302,
 108.6879724298866,
 102.7954460687236,
 113.88976243398722,
 298.85697853063687,
 235.48993714959104,
 376.7296650216803,
 100.17023350737242,
 109.55589375912564,
 367.9563326048619,
 193.2930679074383,
 2172.6815868982603,
 232.46620548581615,
 139.99794833482662,
 106.66785097585141,
 120.22491818029904,
 92.57863094737229,
 132.411617661757,
 275.15016910096205,
 426.31540825606163,
 119.5044339497884,
 91.74498714212461,
 123.4011450708877,
 178.16307398725095,
 281.22416257395327,
 436.2373046875,
 656.3771575631447,
 90.85287591631744,
 1239.0154972014689,
 100.77441295142313,
 187.28516955823187,
 93.91695646020587,
 72.68945608787166,
 99.98884483757142,
 81.43653783211816,
 277.01501682121005,
 91.14734718791875,
 192.1294438630632,
 100.7847794961775,
 904.9482722112662,
 110.05166756836728,
 150.49977215516915,


In [15]:
MSE_array = np.array(MSE_list)
MSE_array

array([ 370.82769706,  233.00636968,  510.64090884,  118.42434722,
        250.89545369,  123.2001602 ,  289.77792309,  611.14527009,
        108.68797243,  102.79544607,  113.88976243,  298.85697853,
        235.48993715,  376.72966502,  100.17023351,  109.55589376,
        367.9563326 ,  193.29306791, 2172.6815869 ,  232.46620549,
        139.99794833,  106.66785098,  120.22491818,   92.57863095,
        132.41161766,  275.1501691 ,  426.31540826,  119.50443395,
         91.74498714,  123.40114507,  178.16307399,  281.22416257,
        436.23730469,  656.37715756,   90.85287592, 1239.0154972 ,
        100.77441295,  187.28516956,   93.91695646,   72.68945609,
         99.98884484,   81.43653783,  277.01501682,   91.14734719,
        192.12944386,  100.7847795 ,  904.94827221,  110.05166757,
        150.49977216,  202.84923334])

In [16]:
print("The mean of the Mean Squared Error list: %.2f" % MSE_array.mean())
print("The standard deviation of the Mean Squared Error list: %.2f" % MSE_array.std())

The mean of the Mean Squared Error list: 281.92
The standard deviation of the Mean Squared Error list: 348.28


# Part C

In [17]:
from sklearn.model_selection import train_test_split

MSE_list=[]

i = 0
while i < 50:
    model = regression_model_A()
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=0)
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, verbose=2)
    scores = model.evaluate(X_test, y_test, verbose=0)
    MSE_list.append(scores)  
    i = i+1

print("Mean Squared Error list:") 
MSE_list

Train on 721 samples, validate on 309 samples
Epoch 1/100
 - 5s - loss: 572265.6761 - val_loss: 439703.7218
Epoch 2/100
 - 0s - loss: 347692.4369 - val_loss: 254410.1201
Epoch 3/100
 - 0s - loss: 189160.1804 - val_loss: 127652.8890
Epoch 4/100
 - 0s - loss: 87445.1588 - val_loss: 53848.9501
Epoch 5/100
 - 0s - loss: 35958.1906 - val_loss: 23564.7980
Epoch 6/100
 - 0s - loss: 17767.3078 - val_loss: 14501.2738
Epoch 7/100
 - 0s - loss: 13072.0931 - val_loss: 12348.3288
Epoch 8/100
 - 0s - loss: 11964.2185 - val_loss: 11633.3776
Epoch 9/100
 - 0s - loss: 11391.4809 - val_loss: 11120.5148
Epoch 10/100
 - 0s - loss: 10878.5589 - val_loss: 10640.1790
Epoch 11/100
 - 0s - loss: 10351.0084 - val_loss: 10157.5075
Epoch 12/100
 - 0s - loss: 9839.8532 - val_loss: 9638.9231
Epoch 13/100
 - 0s - loss: 9334.4289 - val_loss: 9168.5910
Epoch 14/100
 - 0s - loss: 8856.8163 - val_loss: 8710.6108
Epoch 15/100
 - 0s - loss: 8383.7665 - val_loss: 8256.0408
Epoch 16/100
 - 0s - loss: 7924.4121 - val_loss: 7

[291.14360332797645,
 72.86853089070243,
 511.2669301449674,
 161.49731316921395,
 91.14880890830821,
 96.3071842131877,
 98.34731996406629,
 93.08558168380392,
 212.71753137088515,
 96.68179383015556,
 106.05813050501555,
 89.9233741636801,
 83.01576504506725,
 102.09794127825394,
 122.84561300432026,
 97.08614928359738,
 232.82118965815573,
 108.2999381401778,
 437.20809255062954,
 80.95153692547943,
 98.35998957365462,
 150.29815303469167,
 90.06256918305333,
 101.30958073193202,
 133.94840652811487,
 84.87840961098286,
 108.88623864133767,
 102.68453131370174,
 497.7789992051603,
 130.40476011998445,
 101.40178680419922,
 92.64350368907151,
 170.5989128038721,
 286.30785727886706,
 97.69929445137097,
 104.28550433803916,
 118.69669463024943,
 84.11170628618655,
 96.23358502434296,
 70.55048472827306,
 95.68510567871884,
 125.25215040287154,
 101.71018201710723,
 93.21504879306435,
 238.40530536244216,
 1474.8878592580654,
 109.29295060241107,
 94.54923423594256,
 122.84167023692702

In [18]:
MSE_array = np.array(MSE_list)
MSE_array

array([ 291.14360333,   72.86853089,  511.26693014,  161.49731317,
         91.14880891,   96.30718421,   98.34731996,   93.08558168,
        212.71753137,   96.68179383,  106.05813051,   89.92337416,
         83.01576505,  102.09794128,  122.845613  ,   97.08614928,
        232.82118966,  108.29993814,  437.20809255,   80.95153693,
         98.35998957,  150.29815303,   90.06256918,  101.30958073,
        133.94840653,   84.87840961,  108.88623864,  102.68453131,
        497.77899921,  130.40476012,  101.4017868 ,   92.64350369,
        170.5989128 ,  286.30785728,   97.69929445,  104.28550434,
        118.69669463,   84.11170629,   96.23358502,   70.55048473,
         95.68510568,  125.2521504 ,  101.71018202,   93.21504879,
        238.40530536, 1474.88785926,  109.2929506 ,   94.54923424,
        122.84167024,   95.94400916])

In [19]:
print("The mean of the Mean Squared Error list: %.2f" % MSE_array.mean())
print("The standard deviation of the Mean Squared Error list: %.2f" % MSE_array.std())

The mean of the Mean Squared Error list: 169.17
The standard deviation of the Mean Squared Error list: 211.28


# Part D

In [20]:
# define regression model
def regression_model_D():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [28]:
MSE_list=[]

i = 0
while i < 50:    
    print("This is No.", i, "Network trained")
    model = regression_model_D()
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=0)
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, verbose=2)
    scores = model.evaluate(X_test, y_test, verbose=0)
    MSE_list.append(scores)  
    i = i+1        

print("Mean Squared Error list:") 
MSE_list

This is No. 0 Network trained
Train on 721 samples, validate on 309 samples
Epoch 1/50
 - 29s - loss: 1523.0725 - val_loss: 1467.3398
Epoch 2/50
 - 0s - loss: 1478.3071 - val_loss: 1412.6163
Epoch 3/50
 - 0s - loss: 1410.7826 - val_loss: 1331.1189
Epoch 4/50
 - 0s - loss: 1310.4787 - val_loss: 1211.2755
Epoch 5/50
 - 0s - loss: 1166.4588 - val_loss: 1044.6609
Epoch 6/50
 - 0s - loss: 975.3396 - val_loss: 830.4446
Epoch 7/50
 - 0s - loss: 744.1391 - val_loss: 594.8106
Epoch 8/50
 - 1s - loss: 517.2102 - val_loss: 383.0920
Epoch 9/50
 - 0s - loss: 342.5777 - val_loss: 256.8296
Epoch 10/50
 - 0s - loss: 252.8730 - val_loss: 204.5025
Epoch 11/50
 - 0s - loss: 217.5907 - val_loss: 184.9429
Epoch 12/50
 - 1s - loss: 203.0194 - val_loss: 176.3817
Epoch 13/50
 - 1s - loss: 194.0346 - val_loss: 171.9074
Epoch 14/50
 - 0s - loss: 188.4652 - val_loss: 168.8628
Epoch 15/50
 - 0s - loss: 184.0502 - val_loss: 165.1654
Epoch 16/50
 - 0s - loss: 180.5929 - val_loss: 162.4323
Epoch 17/50
 - 0s - loss: 

[114.3113259127225,
 118.94352862904373,
 100.1683305536659,
 112.36244416468352,
 110.46832964258286,
 122.44761704626978,
 124.35021908460698,
 113.66799190978016,
 124.94546190280359,
 120.67898823759703,
 102.99373527946595,
 120.60475753734798,
 123.42073804738067,
 120.72778932639311,
 112.95590328475804,
 114.26437639650018,
 133.75929381237833,
 112.50135282251055,
 92.62209396609211,
 124.9086414077907,
 127.5137535514955,
 128.54280771792514,
 114.04097913229735,
 120.11175825989362,
 124.84072759930756,
 118.84065814465767,
 117.51196343381814,
 99.43359513267345,
 99.32827231644812,
 121.52996364457708,
 124.47610683502889,
 109.82167872950482,
 108.33264666313492,
 122.21417233859066,
 125.76202938240323,
 117.05774380088238,
 126.60673537763577,
 123.11978040775435,
 127.40182601286756,
 105.32633562304055,
 120.18934725171925,
 96.6338303698691,
 121.97242647930257,
 121.97205962640953,
 111.21076822126568,
 104.62162474598314,
 102.86679899345324,
 115.52537104535642,
 

In [29]:
MSE_array = np.array(MSE_list)
MSE_array

array([114.31132591, 118.94352863, 100.16833055, 112.36244416,
       110.46832964, 122.44761705, 124.35021908, 113.66799191,
       124.9454619 , 120.67898824, 102.99373528, 120.60475754,
       123.42073805, 120.72778933, 112.95590328, 114.2643764 ,
       133.75929381, 112.50135282,  92.62209397, 124.90864141,
       127.51375355, 128.54280772, 114.04097913, 120.11175826,
       124.8407276 , 118.84065814, 117.51196343,  99.43359513,
        99.32827232, 121.52996364, 124.47610684, 109.82167873,
       108.33264666, 122.21417234, 125.76202938, 117.0577438 ,
       126.60673538, 123.11978041, 127.40182601, 105.32633562,
       120.18934725,  96.63383037, 121.97242648, 121.97205963,
       111.21076822, 104.62162475, 102.86679899, 115.52537105,
       117.15504989, 120.83992738])

In [30]:
print("The mean of the Mean Squared Error list: %.2f" % MSE_array.mean())
print("The standard deviation of the Mean Squared Error list: %.2f" % MSE_array.std())

The mean of the Mean Squared Error list: 116.32
The standard deviation of the Mean Squared Error list: 9.23
